### ISSUE TITLE
Temperature measurement read

### ISSUE THREAD

**Issue by student3671** [sfera-labs/iono-pi-kernel-module#3]
Hello,
I connected the temperature sensor on the TTL1 port and everything is ok. Instead of using the TTL1 I tried using TTL2. Through a direct connection without changing anything it didn't work, so i modified the **_config.txt_** file as follows:

```bash
dtoverlay=ionopi
```
```bash
dtoverlay=w1-gpio
dtparam=gpiopin=26 #using GPIO26 (TTL2) instead of GPIO4 (default and corresponds to TTL1)
```
Where GPIO 26 corresponds to TTL2 according to the [documentation](https://www.sferalabs.cc/files/ionopi/doc/ionopi-user-guide.pdf).
Checking on:
```bash
ls /sys/bus/w1/devices
```
i can only see the **_w1_bus_master1_** and the device ID ```28-XXXXXXXXXXXX``` is not created.

How can the other TTL ports be enabled and make a configuration to connect more than one temperature sensor?

In addition, I'd also like to power the temperature sensor using the TTL GPIO pins in order to turn it on/off in a controlled way. Even for this case i tried the following procedure:

```bash
echo 478 > /sys/class/gpio/export #GPIO20
echo out > /sys/class/gpio/gpio478/direction
echo 1 > /sys/class/gpio/gpio478/value
```
However, measuring the pin voltage it doesn't result to be high. (Did the same procedure for the other GPIOs, without any success).

Is it possible to achieve a controlled on/off of the device using these GPIO pins and eventually how to control the pins?

**Comment by giampiero7** [comment]
Hello @student3671 ,
You need to move the internal jumpers to select TTL, rather than DI. Please, refer to page 18 of the user guide.
Then you can use the w1-gpio overlay on GPIO 26 as you correctly did.

Having said that, you don't need other TTL inputs to have more sensors, 1-Wire is a bus interface and it allows to have multiple sensors on the same line, so you can simply connect all your sensors to TTL1.

The TTL lines are not conceived to power devices, you might be successful with probes with very very low consumption, but might have unstable results. It would be better to use the 5VOUT output connected to the sensor through one of the relays. Then control the relay for turning on/off the sensor.

Just a note on your final commands: to control GPIO20, you should use "20" for exporting and controlling, not 478.

**Comment by student3671** [comment]
Thank you @giampiero7,  I must've missed the TTL/DI configuration.
For what concerns the GPIO pin number, in my case 478 corresponds to GPIO20. As you rightfully noted, I used 20 and got the following error: `echo: write error: Invalid argument`. Then i understood that the "right" number would be `458 + 20`.

I tried using the relays configuration and basically when i run the following command:
```bash
echo F > /sys/class/ionopi/relay/o1 # tried with echo 1 too
```
the switch doesn't change its state. The `o1` file remains always to `0` even though i don't get any writing errors.

Controlling it throughout the following commands instead, it works just fine:
```bash
echo 475 > /sys/class/gpio/export #about pin number, same discussion even here 458 + 17
echo out > /sys/class/gpio/gpio475/direction
echo 1 > /sys/class/gpio/gpio475/value # echo 1 switch on and echo 0 to switch off
```

**Comment by giampiero7** [comment]
Are you using the Iono Pi board on a Raspberry Pi?
Where did you find the '458 + gpio#' rule?

**Comment by student3671** [comment]
Yes, I'm using a Raspberry Pi.
I found out making some troubleshooting and i noticed that for the `GPIO4` the system was using the number `462`. However in my case the number to add was `458` but i think it changes. Taking a quick looking into 
```bash
ls /sys/class/gpio
```
I found in there `gpiochip458`. Adding things together and some additional tests was able to find the "formula" and the famous number `458`.
I'll get back into this, making a deeper analysis when I have a little bit of time. At the moment I can say that for me it works this way but haven't figured out yet why the GPIO pin numbers changed.
